export const GET_CUSTOMERS_STARTED = "GET_CUSTOMERS_STARTED";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILURE = "GET_CUSTOMERS_FAILURE";
export const SAVE_CUSTOMER_STARTED = "SAVE_CUSTOMER_STARTED";
export const SAVE_CUSTOMER_SUCCESS = "SAVE_CUSTOMER_SUCCESS";
export const SAVE_CUSTOMER_FAILURE = "SAVE_CUSTOMER_FAILURE";
export const UPDATE_CUSTOMER_STARTED = "UPDATE_CUSTOMER_STARTED";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";

export const GET_PROJECTS_STARTED = "GET_PROJECTS_STARTED";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
export const SAVE_PROJECT_STARTED = "SAVE_PROJECT_STARTED";
export const SAVE_PROJECT_SUCCESS = "SAVE_PROJECT_SUCCESS";
export const SAVE_PROJECT_FAILURE = "SAVE_PROJECT_FAILURE";
export const UPDATE_PROJECT_STARTED = "UPDATE_PROJECT_STARTED";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const GET_INVOICES_STARTED = "GET_INVOICES_STARTED";
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS";
export const GET_INVOICES_FAILURE = "GET_INVOICES_FAILURE";
export const SAVE_INVOICE_STARTED = "SAVE_INVOICE_STARTED";
export const SAVE_INVOICE_SUCCESS = "SAVE_INVOICE_SUCCESS";
export const SAVE_INVOICE_FAILURE = "SAVE_INVOICE_FAILURE";
export const UPDATE_INVOICE_STARTED = "UPDATE_INVOICE_STARTED";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_FAILURE = "UPDATE_INVOICE_FAILURE";

export const GET_USER_STARTED = "GET_USER_STARTED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
