export const GET_CUSTOMERS_STARTED = "GET_CUSTOMERS_STARTED";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILURE = "GET_CUSTOMERS_FAILURE";
export const SAVE_CUSTOMER_STARTED = "SAVE_CUSTOMER_STARTED";
export const SAVE_CUSTOMER_SUCCESS = "SAVE_CUSTOMER_SUCCESS";
export const SAVE_CUSTOMER_FAILURE = "SAVE_CUSTOMER_FAILURE";
export const UPDATE_CUSTOMER_STARTED = "UPDATE_CUSTOMER_STARTED";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";
export const SELECT_CUSTOMER = "SELECT_CUSTOMER";
export const TOGGLE_CUSTOMER_CREATION = "TOGGLE_CUSTOMER_CREATION";
export const TOGGLE_CUSTOMER_EDIT = "TOGGLE_CUSTOMER_EDIT";

export const GET_PROJECTS_STARTED = "GET_PROJECTS_STARTED";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
export const SAVE_PROJECT_STARTED = "SAVE_PROJECT_STARTED";
export const SAVE_PROJECT_SUCCESS = "SAVE_PROJECT_SUCCESS";
export const SAVE_PROJECT_FAILURE = "SAVE_PROJECT_FAILURE";
export const UPDATE_PROJECT_STARTED = "UPDATE_PROJECT_STARTED";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";
export const TOGGLE_PROJECT_SELECTION = "TOGGLE_PROJECT_SELECTION";
export const TOGGLE_PROJECT_CREATION = "TOGGLE_PROJECT_CREATION";
export const TOGGLE_PROJECT_EDIT = "TOGGLE_PROJECT_EDIT";
export const DELETE_PROJECT_STARTED = "DELETE_PROJECT_STARTED";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";
export const BULK_UPDATE_PROJECTS_STARTED = "BULK_UPDATE_PROJECTS_STARTED";
export const BULK_UPDATE_PROJECTS_SUCCESS = "BULK_UPDATE_PROJECTS_SUCCESS";
export const BULK_UPDATE_PROJECTS_FAILURE = "BULK_UPDATE_PROJECTS_FAILURE";

export const GET_INVOICES_STARTED = "GET_INVOICES_STARTED";
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS";
export const GET_INVOICES_FAILURE = "GET_INVOICES_FAILURE";
export const SAVE_INVOICE_STARTED = "SAVE_INVOICE_STARTED";
export const SAVE_INVOICE_SUCCESS = "SAVE_INVOICE_SUCCESS";
export const SAVE_INVOICE_FAILURE = "SAVE_INVOICE_FAILURE";
export const UPDATE_INVOICE_STARTED = "UPDATE_INVOICE_STARTED";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_FAILURE = "UPDATE_INVOICE_FAILURE";
export const TOGGLE_INVOICE_CREATION = "TOGGLE_INVOICE_CREATION";

export const GET_USER_STARTED = "GET_USER_STARTED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_STARTED = "LOGOUT_STARTED";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_STARTED = "REGISTER_STARTED";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const AUTHENTICATE_FAILURE = "AUTHENTICATE_FAILURE";
export const AUTHENTICATE_STARTED = "AUTHENTICATE_STARTED";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";

export const EXPAND_ACCORDION = "EXPAND_ACCORDION";
export const FOLD_ACCORDION = "FOLD_ACCORDION";

export const SAVE_USER_STARTED = "SAVE_USER_STARTED";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAILURE = "SAVE_USER_FAILURE";
export const UPDATE_USER_STARTED = "UPDATE_USER_STARTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const TOGGLE_USER_EDIT = "TOGGLE_USER_EDIT";
